export enum Activation {
  None = 'None',
  Linear = 'Linear',
  Step = 'Step',
  ReLU = 'ReLU',
  LeakyReLU = 'LeakyReLU',
  ELU = 'ELU',
  Sigmoid = 'Sigmoid',
  Swish = 'Swish',
  HardSigmoid = 'HardSigmoid',
  Tanh = 'Tanh',
  HardTanh = 'HardTanh',
  Softmax = 'Softmax',
  Gaussian = 'Gaussian',
  OffsetGaussian = 'OffsetGaussian',
  GELU = 'GELU',
  Sine = 'Sine',
  Cos = 'Cos',
  Square = 'Square',
  Abs = 'Abs',
  Softsign = 'Softsign',
  Exp = 'Exp',
  ClippedExp = 'ClippedExp',
  Softplus = 'Softplus',
  Mish = 'Mish',
}
