import type {
  Algorithm,
  ConfigData,
  ConfigFactoryOptions,
  ConfigOptions,
  CoreConfig,
  CoreGenome,
  CoreLink,
  CoreNode,
  CoreState,
  ExtendedState,
  GenomeData,
  GenomeFactoryOptions,
  GenomeOptions,
  LinkFactoryOptions,
  NEATConfigOptions,
  NodeFactoryOptions,
  StateData,
} from '@neat-evolution/core'
import type { Evaluator } from '@neat-evolution/evaluator'

import type { Population } from './Population.js'
import type { PopulationOptions } from './PopulationOptions.js'
import type { ReproducerFactory } from './reproducer/ReproducerFactory.js'

export type PopulationFactory<
  // Genome
  CFO extends ConfigFactoryOptions,
  NCO extends ConfigOptions,
  LCO extends ConfigOptions,
  CD extends ConfigData,
  C extends CoreConfig<CFO, NCO, LCO, CD>,
  NSD,
  LSD,
  NS extends ExtendedState<NSD>,
  LS extends ExtendedState<LSD>,
  SD extends StateData,
  S extends CoreState<NSD, LSD, NS, LS, SD>,
  HND,
  LD,
  GFO extends GenomeFactoryOptions<HND, LD>,
  GO extends GenomeOptions,
  GD extends GenomeData<CD, SD, HND, LD, GFO, GO>,
  // CoreNode
  NFO extends NodeFactoryOptions,
  N extends CoreNode<NFO, NCO, NSD, NS, N>,
  // CoreLink
  LFO extends LinkFactoryOptions,
  L extends CoreLink<LFO, LCO, LSD, LS, L>,
  // CoreGenome
  G extends CoreGenome<
    CFO,
    NCO,
    LCO,
    CD,
    C,
    NSD,
    LSD,
    NS,
    LS,
    SD,
    S,
    HND,
    LD,
    GFO,
    GO,
    GD,
    NFO,
    N,
    LFO,
    L,
    G
  >,
> = (
  createReproducer: ReproducerFactory<
    G,
    Population<
      CFO,
      NCO,
      LCO,
      CD,
      C,
      NSD,
      LSD,
      NS,
      LS,
      SD,
      S,
      HND,
      LD,
      GFO,
      GO,
      GD,
      NFO,
      N,
      LFO,
      L,
      G,
      Algorithm<
        CFO,
        NCO,
        LCO,
        CD,
        C,
        NSD,
        LSD,
        NS,
        LS,
        SD,
        S,
        HND,
        LD,
        GFO,
        GO,
        GD,
        NFO,
        N,
        LFO,
        L,
        G
      >
    >
  >,
  evaluator: Evaluator<any, any, any>,
  neatConfigOptions: NEATConfigOptions,
  populationOptions: PopulationOptions,
  genomeOptions: GO
) => Population<
  CFO,
  NCO,
  LCO,
  CD,
  C,
  NSD,
  LSD,
  NS,
  LS,
  SD,
  S,
  HND,
  LD,
  GFO,
  GO,
  GD,
  NFO,
  N,
  LFO,
  L,
  G,
  Algorithm<
    CFO,
    NCO,
    LCO,
    CD,
    C,
    NSD,
    LSD,
    NS,
    LS,
    SD,
    S,
    HND,
    LD,
    GFO,
    GO,
    GD,
    NFO,
    N,
    LFO,
    L,
    G
  >
>
