name: Release

# Enabled permissions on GITHUB_TOKEN
permissions:
  # To be able to create packages
  packages: write
  # To be able to push to the repo
  contents: write
  # To update the pr description with canary info
  pull-requests: write
  # For pr-check to create a status
  statuses: write
  # Needed to create PR statuses/checks
  checks: write
  # To post comments on PRs
  issues: write

on:
  # Release on push to main
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Prevent the action from storing credentials in a way that's hard to override
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: "https://npm.pkg.github.com"
          scope: "@neat-evolution"
      
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.neat-evolution.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.neat-evolution.npmAlwaysAuth true
          yarn config set npmScopes.neat-evolution.npmAuthToken $NPM_AUTH_TOKEN
          yarn config set npmScopes.heygrady.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.heygrady.npmAlwaysAuth true
          yarn config set npmScopes.heygrady.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get yarn cache directory
        run: echo "LOOKUP_YARN_CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_ENV

      - name: Cache TurboRepo
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            ${{ env.LOOKUP_YARN_CACHE_FOLDER }}
            node_modules
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Set the name, email, and URL with PAT
      - name: Set git credentials
        run: |
          git config user.name "Release Bot"
          git config user.email "github@heygrady.net"
          git remote set-url origin "https://$BEACHBALL_GH_TOKEN@github.com/neat-evolution/neat-js"
        env:
          BEACHBALL_GH_TOKEN: ${{ secrets.BEACHBALL_GH_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable --refresh-lockfile

      - name: Build (all)
        run: yarn build

      # Pass the token on the command line for publishing
      - name: Publish
        run: 'yarn beachball publish --message "chore: publish [skip ci]" --token "$NPM_TOKEN"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # After publishing, install dependencies to update the yarn.lock file
      - name: Update yarn.lock
        run: yarn install --no-immutable --mode=update-lockfile

      # Check for changes in the yarn.lock file
      - name: Check for yarn.lock changes
        run: |
          if git diff --name-only | grep -q 'yarn.lock'; then
            echo "MODIFIED=true" >> $GITHUB_ENV
          fi

      # Commit and push the updated yarn.lock file, if it has changed
      - name: Commit yarn.lock changes
        if: env.MODIFIED == 'true'
        run: |
          git add yarn.lock
          git commit -m "chore: update yarn.lock [skip ci]"
          git push
